spring:
   datasource:
      primary:
         url: jdbc:mysql://127.0.0.1:3306/jeecf?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
         username: root
         password: 12345678
   redis: #redis配置
      host: 127.0.0.1
      port: 6379
 
file:
   osgi:
      upload:
         basePath: /
      suffix: .jar
   tmpl:
      download:
         prefix:
            path: /Users/jianyiming/tmp/jeecm
      upload:
         path: /Users/jianyiming/tmp/template/real
         tmp:
            path: /Users/jianyiming/tmp/template/tmp
      suffix:
         name: zip
         
encrypt:
   key: 12345678   