spring:
   datasource:
      primary:
         url: jdbc:mysql://127.0.0.1:3306/jeecf-qa?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
         username: root
         password: 12345678
   redis: #redis配置
      host: 127.0.0.1
      port: 6379